**NOTE: This is not the exact solution - individual cells have been used in random order** *italicized text*

## Setup + dataset imports

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
train_df = pd.read_csv('/content/drive/My Drive/HackerEarth Machine Learning Pet Adoption/Dataset/train.csv',parse_dates=True)
test_df = pd.read_csv('/content/drive/My Drive/HackerEarth Machine Learning Pet Adoption/Dataset/test.csv',parse_dates=True)

## Data Preprocessing

In [ ]:
train_df['pet_id'] = train_df['pet_id'].apply(lambda x: x.strip('ANSL_')).astype('int')
test_df['pet_id'] = test_df['pet_id'].apply(lambda x: x.strip('ANSL_')).astype('int')

In [ ]:
train_df['issue_date'] = train_df['issue_date'].apply(lambda x: x.strip(' 00:00:00	'))
test_df['issue_date'] = test_df['issue_date'].apply(lambda x: x.strip(' 00:00:00	'))

In [ ]:
train_df['issue_date'] = pd.to_datetime(train_df['issue_date'])
test_df['issue_date'] = pd.to_datetime(test_df['issue_date'])

In [ ]:
train_df.head()

pet_id issue_date         listing_date  ...  X2 breed_category  pet_category
0   69903 2016-07-10  2016-09-21 16:25:00  ...   9            0.0             1
1   66892 2013-11-21  2018-12-27 17:47:00  ...   9            0.0             2
2   69750 2014-09-28  2016-10-19 08:24:00  ...   4            2.0             4
3   71623 2016-12-31  2019-01-25 18:30:00  ...   1            0.0             2
4   57969 2017-09-28  2017-11-19 09:38:00  ...   4            0.0             1

[5 rows x 11 columns]

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18834 entries, 0 to 18833
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype         
---  ------          --------------  -----         
 0   pet_id          18834 non-null  int64         
 1   issue_date      18834 non-null  datetime64[ns]
 2   listing_date    18834 non-null  object        
 3   condition       17357 non-null  float64       
 4   color_type      18834 non-null  object        
 5   length(m)       18834 non-null  float64       
 6   height(cm)      18834 non-null  float64       
 7   X1              18834 non-null  int64         
 8   X2              18834 non-null  int64         
 9   breed_category  18834 non-null  float64       
 10  pet_category    18834 non-null  int64         
dtypes: datetime64[ns](1), float64(4), int64(4), object(2)
memory usage: 1.6+ MB


In [ ]:
train_df['listing_date'] = pd.to_datetime(train_df['listing_date'],utc=True)
test_df['listing_date'] = pd.to_datetime(test_df['listing_date'],utc=True)

In [ ]:
train_df['breed_category'] = train_df['breed_category'].astype('int')
#test_df['breed_category'] = test_df['breed_category'].astype('int')

In [ ]:
test_df['issue_date']= pd.to_datetime(test_df['issue_date']).astype(int)
train_df['issue_date'] = pd.to_datetime(train_df['issue_date']).astype(int)

In [ ]:
test_df['listing_date']= pd.to_datetime(test_df['listing_date']).astype(int)
train_df['listing_date'] = pd.to_datetime(train_df['listing_date']).astype(int)

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
train_df['color_type'] = pd.DataFrame(encoder.fit_transform(pd.DataFrame(train_df['color_type'])))
test_df['color_type'] = pd.DataFrame(encoder.transform(pd.DataFrame(test_df['color_type'])))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')
imputed_train_df = train_df
imputed_test_df = test_df
imputed_train_df['condition'] = pd.DataFrame(imputer.fit_transform(pd.DataFrame(imputed_train_df['condition'])))
imputed_test_df['condition'] = pd.DataFrame(imputer.transform(pd.DataFrame(test_df['condition'])))

In [ ]:
imputed_train_df['condition'] = imputed_train_df['condition'].astype('int')
imputed_test_df['condition'] = imputed_test_df['condition'].astype('int')

# Data Copies for Feature Engineering

In [ ]:
train_df_copy = train_df.copy()
test_df_copy = test_df.copy()

In [ ]:
train_df_copy['stayed_in_shelter'] = train_df_copy['listing_date']-train_df_copy['issue_date']
test_df_copy['stayed_in_shelter'] = test_df_copy['listing_date']-test_df_copy['issue_date']

In [ ]:
train_df_copy_1 = train_df_copy.copy()
test_df_copy_1 = test_df_copy.copy()
train_df_copy_2 = train_df_copy.copy()
test_df_copy_2 = test_df_copy.copy()

In [ ]:
train_df_copy_1['size'] = (train_df_copy_1['length(m)']**2)*train_df_copy_1['height(cm)']/100
test_df_copy_1['size'] = (test_df_copy_1['length(m)']**2)*test_df_copy_1['height(cm)']/100

In [ ]:
train_df_copy_2['size'] = (train_df_copy_2['length(m)'])*train_df_copy_2['height(cm)']/100
test_df_copy_2['size'] = (test_df_copy_2['length(m)'])*test_df_copy_2['height(cm)']/100

## Dropping for a while

In [ ]:
train_df_copy_1['stayed_in_shelter'] = train_df_copy_1['listing_date']-train_df_copy_1['issue_date']
test_df_copy_1['stayed_in_shelter'] = test_df_copy_1['listing_date']-test_df_copy_1['issue_date']
train_df_copy_2['stayed_in_shelter'] = train_df_copy_2['listing_date']-train_df_copy_2['issue_date']
test_df_copy_2['stayed_in_shelter'] = test_df_copy_2['listing_date']-test_df_copy_2['issue_date']

In [ ]:
Y1 = train_df_copy_1['breed_category']
Y2 = train_df_copy_1['pet_category']
X_train = train_df_copy_1.drop(columns=['breed_category','pet_category'])
X_test = test_df_copy_1

# Arranging Data as features and labels

In [ ]:
Y1 = train_df_copy_1['breed_category']
Y2 = train_df_copy_1['pet_category']
X_train_1 = train_df_copy_1.drop(columns=['breed_category','pet_category'])
X_test_1 = test_df_copy_1
X_train_2 = train_df_copy_2.drop(columns=['breed_category','pet_category'])
X_test_2 = test_df_copy_2

# Experimentation:

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier()
print(cross_val_score(model,imputed_X_train_1,Y1,cv=5))
print(cross_val_score(model,imputed_X_train_2,Y1,cv=5))
print(cross_val_score(model,imputed_X_train_1,Y2,cv=5))
print(cross_val_score(model,imputed_X_train_2,Y2,cv=5))

In [ ]:
from xgboost import XGBClassifier

model = XGBClassifier()
#print(size = )
print(cross_val_score(model,X_train_1,Y1,cv=5))
print(cross_val_score(model,X_train_2,Y1,cv=5))
print(cross_val_score(model,X_train_1,Y2,cv=5))
print(cross_val_score(model,X_train_2,Y2,cv=5))

[0.89779666 0.90814972 0.90735333 0.90363685 0.89697292]
[0.89726573 0.90496416 0.90921157 0.90257499 0.89537971]
[0.88638174 0.89195646 0.89009822 0.88717813 0.88555497]
[0.88823998 0.89328378 0.89116007 0.88558535 0.88528943]


In [ ]:
import lightgbm as lgb

model = lgb.LGBMClassifier()
print(cross_val_score(model,X_train_1,Y1,cv=5))
print(cross_val_score(model,X_train_2,Y1,cv=5))
print(cross_val_score(model,X_train_1,Y2,cv=5))
print(cross_val_score(model,X_train_2,Y2,cv=5))

[0.89328378 0.90416777 0.90496416 0.9126626  0.89591078]
[0.89726573 0.90522963 0.90284046 0.90761879 0.89325544]
[0.90655694 0.91000796 0.90841518 0.90549509 0.90387679]
[0.90363685 0.90735333 0.90841518 0.90708787 0.90308019]


# Not Worth using an imputer explicitely

In [ ]:
from sklearn.impute import KNNImputer
imputed_X_train_1 = X_train_1
imputed_X_test_1 = X_test_1
imputed_X_train_2 = X_train_2
imputed_X_test_2 = X_test_2
imputer = KNNImputer()
imputed_X_train_1['condition'] = pd.DataFrame(imputer.fit_transform(pd.DataFrame(X_train_1['condition'])))
imputed_X_test_1['condition'] = pd.DataFrame(imputer.transform(pd.DataFrame(X_test_1['condition'])))
imputed_X_train_2['condition'] = pd.DataFrame(imputer.fit_transform(pd.DataFrame(X_train_2['condition'])))
imputed_X_test_2['condition'] = pd.DataFrame(imputer.transform(pd.DataFrame(X_test_2['condition'])))
imputed_X_train_1.columns = X_train_1.columns
imputed_X_test_1.columns = X_test_1.columns
imputed_X_train_2.columns = X_train_2.columns
imputed_X_test_2.columns = X_test_2.columns

In [ ]:
imputed_X_train_1['condition'] = imputed_X_train_1['condition'].astype('int')
imputed_X_test_1['condition'] = imputed_X_test_1['condition'].astype('int')
imputed_X_train_2['condition'] = imputed_X_train_2['condition'].astype('int')
imputed_X_test_2['condition'] = imputed_X_test_2['condition'].astype('int')

In [ ]:
X_train_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18834 entries, 0 to 18833
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   pet_id             18834 non-null  int64  
 1   issue_date         18834 non-null  int64  
 2   listing_date       18834 non-null  int64  
 3   condition          18834 non-null  int64  
 4   color_type         18834 non-null  int64  
 5   length(m)          18834 non-null  float64
 6   height(cm)         18834 non-null  float64
 7   X1                 18834 non-null  int64  
 8   X2                 18834 non-null  int64  
 9   size               18834 non-null  float64
 10  stayed_in_shelter  18834 non-null  int64  
dtypes: float64(3), int64(8)
memory usage: 1.6 MB


In [ ]:
from sklearn.ensemble import RandomForestClassifier
#lasso = linear_model.Lasso()
model = RandomForestClassifier()
print(cross_val_score(model,X_train_1,Y1,cv=5))
print(cross_val_score(model,X_train_2,Y1,cv=5))
print(cross_val_score(model,X_train_1,Y2,cv=5))
print(cross_val_score(model,X_train_2,Y2,cv=5))

[0.88266525 0.89089461 0.89514202 0.89036368 0.88050982]
[0.88478896 0.89354924 0.89328378 0.89248739 0.88077536]
[0.87709052 0.88346164 0.88346164 0.87523228 0.87918216]
[0.88027608 0.88505442 0.88027608 0.86886116 0.87307488]


In [ ]:
from xgboost import XGBClassifier

model = XGBClassifier()
print(cross_val_score(model,X_train_1,Y1,cv=5))
print(cross_val_score(model,X_train_2,Y1,cv=5))
print(cross_val_score(model,X_train_1,Y2,cv=5))
print(cross_val_score(model,X_train_2,Y2,cv=5))

[0.88823998 0.8996549  0.89885851 0.88585081 0.88183749]
[0.88823998 0.89885851 0.89540749 0.88744359 0.88183749]
[0.88531988 0.88877091 0.8866472  0.88186886 0.87997876]
[0.88531988 0.88850544 0.88611627 0.88266525 0.88024429]


In [ ]:
import lightgbm as lgb

model = lgb.LGBMClassifier()
print(cross_val_score(model,X_train_1,Y1,cv=5))
print(cross_val_score(model,X_train_2,Y1,cv=5))
print(cross_val_score(model,X_train_1,Y2,cv=5))
print(cross_val_score(model,X_train_2,Y2,cv=5))

[0.88054154 0.89567295 0.89248739 0.89354924 0.87944769]
[0.88930183 0.89116007 0.89354924 0.89726573 0.88130643]
[0.89726573 0.90629148 0.90655694 0.90018582 0.89962825]
[0.90124768 0.90708787 0.90708787 0.90098221 0.89936272]


# Final_preds

In [ ]:
model1 = XGBClassifier()
model1.fit(X_train,Y1)
preds_1 = model1.predict(X_test)

In [ ]:
import lightgbm as lgb
model2 = lgb.LGBMClassifier()
model2.fit(X_train,Y2)
preds_2 = model2.predict(X_test)

In [ ]:
test_submit = pd.read_csv('/content/drive/My Drive/HackerEarth Machine Learning Pet Adoption/Dataset/test.csv')
test_pet_ids = pd.DataFrame(test_submit['pet_id'])

In [ ]:
test_pet_ids['breed_category'] = preds_1
test_pet_ids['pet_category'] = preds_2

In [ ]:
test_pet_ids.head()

pet_id  breed_category  pet_category
0  ANSL_75005               1             2
1  ANSL_76663               0             1
2  ANSL_58259               0             2
3  ANSL_67171               0             2
4  ANSL_72871               0             2

In [ ]:
test_pet_ids.to_csv("pred_5_xgb_lgb.csv",index=False)

In [ ]:
#Data_Viz
